Dev: normalize scripts

diff --git a/script/fmt b/script/fmt
--- a/script/fmt
+++ b/script/fmt
@@ -1,2 +1,10 @@
 #!/bin/bash
-bundle exec rubocop $@
+set -e
+
+echo "Rubocop $(bundle exec rubocop --version)"
+bundle exec rubocop -S -D -E $@
+success=$?
+if ((success != 0)); then
+   echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
+fi
+exit $success
